/*
 * Created on 2005. 1. 17
 */
package org.uwdl.parser;

import org.uwdl.parser.ast.UActivate;
import org.uwdl.parser.ast.UActivator;
import org.uwdl.parser.ast.UAndConstraint;
import org.uwdl.parser.ast.UBaseOntologies;
import org.uwdl.parser.ast.UCase;
import org.uwdl.parser.ast.UCondition;
import org.uwdl.parser.ast.UConstraint;
import org.uwdl.parser.ast.UContext;
import org.uwdl.parser.ast.UCopy;
import org.uwdl.parser.ast.UDeactivate;
import org.uwdl.parser.ast.UDocumentation;
import org.uwdl.parser.ast.UEvent;
import org.uwdl.parser.ast.UFlow;
import org.uwdl.parser.ast.UFrom;
import org.uwdl.parser.ast.UInitialize;
import org.uwdl.parser.ast.UInput;
import org.uwdl.parser.ast.UInvoke;
import org.uwdl.parser.ast.ULink;
import org.uwdl.parser.ast.ULocator;
import org.uwdl.parser.ast.UMessage;
import org.uwdl.parser.ast.UNSync;
import org.uwdl.parser.ast.UNode;
import org.uwdl.parser.ast.UNotConstraint;
import org.uwdl.parser.ast.UObject;
import org.uwdl.parser.ast.UOntology;
import org.uwdl.parser.ast.UOrConstraint;
import org.uwdl.parser.ast.UOutput;
import org.uwdl.parser.ast.UParallel;
import org.uwdl.parser.ast.UPart;
import org.uwdl.parser.ast.UPortType;
import org.uwdl.parser.ast.URule;
import org.uwdl.parser.ast.UServiceProvider;
import org.uwdl.parser.ast.UServiceProviderType;
import org.uwdl.parser.ast.USink;
import org.uwdl.parser.ast.USource;
import org.uwdl.parser.ast.USubject;
import org.uwdl.parser.ast.USynchronize;
import org.uwdl.parser.ast.UTo;
import org.uwdl.parser.ast.UTransition;
import org.uwdl.parser.ast.UUWDL;
import org.uwdl.parser.ast.UVariable;
import org.uwdl.parser.ast.UVerb;
import org.uwdl.parser.ast.UWait;

public interface uWDLVisitor {
	public void visit(UActivate activate);
	public void visit(UCase uCase);
	public void visit(UCondition condition);
	public void visit(UAndConstraint andCondition);
	public void visit(UOrConstraint orCondition);
	public void visit(UNotConstraint notCondition);
	public void visit(UConstraint constraint);
	public void visit(UContext context);
	public void visit(UActivator activator);
	public void visit(UBaseOntologies baseOntologies);
	public void visit(UDocumentation description);
	public void visit(UEvent event);
	public void visit(UDeactivate deactivate);
	public void visit(UFlow flow);
	public void visit(ULink link);
	public void visit(UFrom from);
	public void visit(UNode node);
	public void visit(UObject object);
	public void visit(UInitialize initialize);
	public void visit(ULocator locator);
	public void visit(UPortType portType);
	public void visit(UMessage message);
	public void visit(UPart part);
	public void visit(UServiceProvider serviceProvider);
	public void visit(URule rule);
	public void visit(UServiceProviderType serviceProviderType);
	public void visit(USink sink);
	public void visit(USource source);
	public void visit(UVariable variable);
	public void visit(USubject subject);
	public void visit(UUWDL uwdl);
	public void visit(UVerb verb);
	public void visit(UCopy copy);
	public void visit(UTo to);
	public void visit(UWait wait);
	public void visit(UInvoke invoke);
	public void visit(UOntology ontology);
	public void visit(UInput input);
	public void visit(UOutput output);
	public void visit(USynchronize synchronize);
	public void visit(UParallel parallel);
	public void visit(UTransition transition);
	public void visit(UNSync nSync);
}
